spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.5.207.158:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  hikari:
    # 连接池最大连接数，默认是 10
    maximum-pool-size: 60
    # 链接超时时间，默认 30000(30 秒)
    connection-timeout: 60000
    # 空闲连接存活最大时间，默认 600000(10 分钟)
    idle-timeout: 60000
    # 连接将被测试活动的最大时间量
    validation-timeout: 3000
    # 此属性控制池中连接的最长生命周期，值 0 表示无限生命周期，默认 1800000(30 分钟)
    max-lifetime: 1800000
    # 连接到数据库时等待的最长时间(秒)
    login-timeout: 5
    # 池中维护的最小空闲连接数
    minimum-idle: 10

  cloud:
    nacos:
      discovery:
        server-addr: 121.5.207.158:8848
  application:
    name: gulimall-product

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      # 逻辑已删除值(默认为 1)
      logic-delete-value: 1
      # 逻辑未删除值(默认为 0)
      logic-not-delete-value: 0

server:
  port: 10000