spring:
  cloud:
    gateway:
      routes:
        - id: baidu_route
          uri: http://www.baidu.com
          predicates:
            - Query=uri, baidu

        - id: qq_route
          uri: http://qq.com
          predicates:
            - Query=uri, qq
server:
  port: 88
