spring:
  cloud:
    nacos:
      discovery:
        server-addr: 121.5.207.158:8848

      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: alibaba-gulimall
  application:
    name: gulimall-third-party

server:
  port: 30000


logging:
  level:
    com.smxy.gulimall: debug

