services:
  #服务名称
  db:
    #docker 镜像名称
    image: mysql:5.7
    #重启docker时，自动启动相关容器
    restart: always
    #对应-i
    stdin_open: true
    #对应-t
    tty: true
    #容器名称
    container_name: mysql
    #container内的root拥有真正的root权限
    privileged: true
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./mysql/my.cnf:/etc/mysql/my.cnf"
      - "./mysql/conf:/etc/mysql/conf.d"
      - "./mysql/logs:/var/log/mysql"
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/dbback:/opt/dbback"
    networks:
      - net-my
    
networks:
  net-my:
      
    