services:
  nginx:
    image: nginx:1.23.1
    stdin_open: true
    tty: true
    privileged: true
    restart: always
    container_name: nginx

    ports:
      - "443:443"
      - "8080:8080"
      
    environment:
      TZ: "Asia/Shanghai"
    
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    
    networks:
      - net-my

networks:
  net-my: